In [8]:
#1
'''For the given NumPy array find all complex and real numbers. Also test whether a given
number is a scalar type or not.
'''
import numpy as np
a=np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
iscomplex=[]
isreal=[]
isscalar=[]
for i in a:
    if np.iscomplex(i):
        iscomplex.append(i)
    elif np.isreal(i):
        isreal.append(i)
    elif np.isscalar(i)==True:
        isscalar.append(i)
print('iscomplex ',iscomplex)
print('isreal',isreal)
print('isscalar',isscalar)
print(np.isscalar(4.5+0j))

iscomplex  [(1+1j), 2j]
isreal [(1+0j), (4.5+0j), (3+0j), (2+0j)]
isscalar []
True


In [14]:
#2
'''Write a NumPy program to create an element-wise comparison (greater, greater_equal, less
and less_equal) of two given arrays.
'''
arr1=np.random.randint(0,20,10)
arr2=np.random.randint(0,20,10)
print(arr1,'&',arr2)

greater=np.greater(arr1,arr2)
greater_equal=np.greater_equal(arr1,arr2)
less=np.less(arr1,arr2)
less_equal=np.less_equal(arr1,arr2)

print('greater  ',greater)
print('greater_equal  ',greater_equal)
print('less  ',less)
print('less_equal  ',less_equal)


[16  8  3  4  6  1 14  9  2 14] & [15 18 16 15 14 15 10  5 12  0]
greater   [ True False False False False False  True  True False  True]
greater_equal   [ True False False False False False  True  True False  True]
less   [False  True  True  True  True  True False False  True False]
less_equal   [False  True  True  True  True  True False False  True False]


In [17]:
#3
'''Create a NumPy array of 10 zeros,10 ones, 10 fives.
'''
zeros=np.zeros(10)
ones=np.ones(10)
fives=ones*5
print(zeros,'\n',ones,'\n',fives)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [18]:
#4
'''Create a vector of size 10 with all zeros and update sixth value to 11.
'''
zeros=np.zeros(10)
zeros[5]=11
zeros

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

In [20]:
#5
'''Create a n-sized vector with random numbers from normal distribution and reverse it.
'''
n=int(input('n='))
normal = np.random.normal(10, 0.5, n)

print(normal)
rev=np.flip(normal, axis=None)
print(rev)

n=5
[ 9.42847504  9.75851169  9.8859506  10.32105847 10.11470814]
[10.11470814 10.32105847  9.8859506   9.75851169  9.42847504]


In [28]:
#6
'''Add a border with zeros to the given square NumPy matrix.

Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]
'''
n=int(input('n='))
arr=np.ones((n,n))
matrix=np.empty((n+2,n+2))
for i in range(n+2):
    for j in range(n+2):
        if i==0 or j==0 or i==n+1 or j==n+1:
            matrix[i][j]=0
        else:
            matrix[i][j]=arr[i-1][j-1]
print(matrix)

n=4
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
#7
'''Create a square NumPy matrix and fill it with a checkerboard pattern.

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
'''
import numpy as np
matrix=np.ones((8,8),dtype=np.int16)

for i in range(8):
    for j in range(i%2,8,2):
        matrix[i][j]=0
print(matrix)            

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [31]:
#8
'''Convert the Centigrade degrees NumPy array into Fahrenheit degrees. Here is the formula to
convert: .
F = C*9/5+ 32
'''
centig=np.random.randint(-5,20,10)
fahren=centig*9/5+32
print(centig)
print(fahren)

[ 5  3  0 14  3 13 12  0 10  8]
[41.  37.4 32.  57.2 37.4 55.4 53.6 32.  50.  46.4]


In [34]:
#9
'''Write a NumPy program to test whether each element of a 1-D array is also present in a
second array.
'''
arr1=np.random.randint(1,20,10)
arr2=np.random.randint(1,20,100)
t=True
for i in arr1:
    if i not in arr2:
        t=False
        break
print(t)

True


In [38]:
#10
'''Write a NumPy program to find equal values between two arrays.
'''
arr1=np.random.randint(1,20,10)
arr2=np.random.randint(1,20,10)
print(arr1)
print(arr1)

greater=np.equal(arr1,arr2)
equal=[]
for i in range(len(greater)):
    if greater[i]:
        equal.append(arr1[i])
print(greater)


[12  5  7 18  8 19  4  7  2 13]
[12  5  7 18  8 19  4  7  2 13]
[False False False False False False False False  True False]
